#!/bin/bash

####################################
# Set these variables appropriately
####################################
# The main thesis file that includes all others
export MAIN_THESIS_FILE=""
# The full path to the ThesisMeter repository
export REPO_DIR=""
# Your github user
export GIT_USER=""
# Your github password. This file is excluded from the repo, so it will never be uploaded.
export GIT_PWD=""

####################################
# Defaults 
####################################
# These variables point to resources withing this repo. 
# You should not need to change them.

# The data file in which statistics will be appended every day
export DATA_FILE="$REPO_DIR/data.csv"
# The path of the figure that will be produced
export FIG_WORD_COUNT="$REPO_DIR/word_count.png"
# Path to the script that plots the results. It's in the repo.
export PLOT_WORD_COUNT="$REPO_DIR/plot_word_count.py"

